remove empty commit for now

diff --git a/.github/workflows/labeler.yml b/.github/workflows/labeler.yml
--- a/.github/workflows/labeler.yml
+++ b/.github/workflows/labeler.yml
@@ -24,14 +24,14 @@ jobs:
         run: |
           git config --local user.email "1439809+joergi@users.noreply.github.com"
           git config --local user.name "Joergi via GitHub Actions"
-      - name: empty commit
-        if: success() || failure()
-        run: |
-          git fetch
-          git checkout ${{ github.head_ref }}
-          git pull
-          git commit --allow-empty -m "trigger GitHub actions"
-          git push origin HEAD:${{ github.head_ref }}
-        env:
-          GH_TOKEN: ${{ secrets.PAT }}
+#      - name: empty commit
+#        if: success() || failure()
+#        run: |
+#          git fetch
+#          git checkout ${{ github.head_ref }}
+#          git pull
+#          git commit --allow-empty -m "trigger GitHub actions"
+#          git push origin HEAD:${{ github.head_ref }}
+#        env:
+#          GH_TOKEN: ${{ secrets.PAT }}
 
